# Runs various checks against any new code.
# Creates a GitHub release named nightly, for the sake of testing in external projects.

name: Check

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 18
          # 'registry-url' is required for 'npm publish'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - run: npm run schema && git diff --exit-code src/testing/schema.ts
      - run: npm test
      - run: npm pack
      - run: git tag -f nightly
      - run: git push -f origin nightly
      - uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: '*.tgz'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: nightly
          tag: nightly
