name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - run: npm test
      - run: npm pack
      - run: git tag -f nightly
      - run: git push -f origin nightly
      - uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: '*.tgz'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: nightly
          tag: nightly
      - if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: '*.tgz'
          token: ${{ secrets.GITHUB_TOKEN }}
