name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - run: npm test
      - run: npm pack
      - uses: ncipollo/release-action@v1
        with:
          artifacts: '*.tgz'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: ${{ github.ref }}
